fileID=fopen('Text.tex','w+');
fprintf(fileID,'\\documentclass[13pt,a4paper]{article}\n');
fprintf(fileID,'\\usepackage[utf8]{vietnam}\n');
fprintf(fileID,'\\usepackage{amsmath}\n');
fprintf(fileID,'\\usepackage{amsfonts}\n');
fprintf(fileID,'\\usepackage{amssymb}\n');
fprintf(fileID,'\\usepackage{graphicx}\n');
fprintf(fileID,'\\usepackage[left=2cm,right=2cm,top=2cm,bottom=2cm]{geometry}\n');
fprintf(fileID,'\\usepackage[unicode]{hyperref}\n');
fprintf(fileID,'\\setlength{\\parindent}{0pt}\n');
fprintf(fileID,'\\begin{document}\n');
fprintf(fileID,'Vien dep trai\n');
